// Form1.FileCopy.cs
// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace U盘文件复制
{
    partial class Form1
    {
        // 文件复制相关字段
        private string _logPath;
        private int _totalFiles = 0;
        private int _successCount = 0;
        private int _failureCount = 0;
        private int _currentSpeedLimit = 2 * 1024 * 1024; // 默认2 MB/秒

        /// <summary>
        /// 执行文件复制（使用当前全局存储目标 _currentDestination）
        /// </summary>
        /// <param name="specificDrive">指定要复制的驱动器，为null时复制所有可移动驱动器</param>
        private async Task CopyFiles(DriveInfo specificDrive = null)
        {
            await CopyFiles(specificDrive, _currentDestination);
        }

        /// <summary>
        /// 执行文件复制到指定存储目标
        /// </summary>
        private async Task CopyFiles(DriveInfo specificDrive, IFileDestination destination)
        {
            if (destination == null)
            {
                LogMessage("错误：未设置文件存储目标", true);
                return;
            }

            try
            {
                _cts.Token.ThrowIfCancellationRequested();
                _logPath = GetLogFilePath(destination);
                LogMessage($"==== 开始复制 {DateTime.Now:yyyy-MM-dd HH:mm:ss} ====", true);

                _totalFiles = 0;
                _successCount = 0;
                _failureCount = 0;
                UpdateCountDisplay();

                // 本地存储需要验证目录，服务器存储不需要
                if (destination is LocalFileDestination && !ValidateTargetDirectory()) return;

                var extensions = GetSelectedExtensions().ToList();
                var searchOptions = extensions.Contains(AllFilesPattern)
                    ? new[] { AllFilesPattern }
                    : extensions.Distinct().ToArray();

                var drives = specificDrive != null
                    ? new[] { specificDrive }
                    : GetRemovableDrives();

                foreach (var drive in drives)
                {
                    _cts.Token.ThrowIfCancellationRequested();
                    LogMessage($"发现U盘：{drive.Name}", true);

                    // 记录目录树（仅本地存储支持）
                    if (destination is LocalFileDestination && _createDirectoryTree)
                        await RecordDirectoryTree(drive);

                    if (ContainsSpecialFile(drive, out var actionType))
                    {
                        if (actionType == FileActionType.StopCopy)
                        {
                            LogMessage($"检测到阻止复制文件，跳过该U盘：{drive.Name}", true);
                            continue;
                        }
                        // ReverseCopy 已在 HandleUsbEvent 中处理，此处不应到达
                    }

                    // 构造相对根路径：本地模式用绝对路径，远程模式只用文件夹名（服务器有自己的存储根）
                    string folderName = CreateDriveFolderName(drive);
                    string driveFolder = destination is LocalFileDestination
                        ? Path.Combine(textBox2.Text, folderName)
                        : folderName;
                    await CopyDirectoryAsync(drive.RootDirectory, driveFolder, searchOptions, destination);
                }
            }
            catch (OperationCanceledException)
            {
                LogMessage("用户取消操作", true);
            }
            catch (Exception ex)
            {
                LogMessage($"全局错误：{ex.Message}", true);
            }
            finally
            {
                LogMessage($"一共复制{_totalFiles}文件，成功{_successCount}个，失败{_failureCount}个", true);
                LogMessage($"==== 复制完成 {DateTime.Now:yyyy-MM-dd HH:mm:ss} ====\n", true);
            }
        }

        /// <summary>
        /// 反向复制（从本地备份到U盘）
        /// </summary>
        private async Task ReverseCopyFromLocalToUsb(DriveInfo usbDrive)
        {
            try
            {
                LogMessage($"检测到反向复制标记，开始反向复制...", true);

                string usbRoot = usbDrive.RootDirectory.FullName;
                string localRoot = GetLocalBackupPath(usbDrive);

                if (!Directory.Exists(localRoot))
                {
                    LogMessage($"找不到对应的本地备份目录：{localRoot}", true);
                    return;
                }

                string markerPath = Path.Combine(usbRoot, _reverseCopyMarker);
                if (File.Exists(markerPath))
                {
                    LogMessage($"该U盘已完成反向复制（检测到标记文件 {_reverseCopyMarker}）", true);
                    return;
                }

                try
                {
                    File.WriteAllText(markerPath, $"反向复制完成于: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
                }
                catch (Exception ex)
                {
                    LogMessage($"创建标记文件失败: {ex.Message}", true);
                }

                var extensions = GetSelectedExtensions().ToList();
                var searchOptions = extensions.Contains(AllFilesPattern)
                    ? new[] { AllFilesPattern }
                    : extensions.Distinct().ToArray();

                // 反向复制时，目标为本地U盘，使用 LocalFileDestination
                var localDestination = new LocalFileDestination(usbRoot);
                await CopyDirectoryAsync(new DirectoryInfo(localRoot), "", searchOptions, localDestination, true, 0);

                LogMessage($"反向复制完成：{localRoot} -> {usbRoot}", true);
            }
            catch (Exception ex)
            {
                LogMessage($"反向复制失败：{ex.Message}", true);
            }
        }

        /// <summary>
        /// 异步复制目录
        /// </summary>
        private async Task CopyDirectoryAsync(
            DirectoryInfo source,
            string relativeTargetDir,     // 相对于存储根目录的路径（例如 "U盘A/文件夹1"）
            string[] searchPatterns,
            IFileDestination destination,
            bool isReverseCopy = false,
            int currentDepth = 0)
        {
            try
            {
                // 递归复制文件
                await CopyFilesWithPatternsAsync(source, relativeTargetDir, searchPatterns, destination, isReverseCopy);
                await ProcessSubdirectoriesAsync(source, relativeTargetDir, searchPatterns, destination, isReverseCopy, currentDepth);
            }
            catch (Exception ex)
            {
                LogMessage($"目录处理失败: {source.FullName} | 错误：{ex.Message}", true);
            }
        }

        private async Task CopyFilesWithPatternsAsync(
            DirectoryInfo source,
            string relativeDirPath,
            string[] searchPatterns,
            IFileDestination destination,
            bool isReverseCopy)
        {
            foreach (var pattern in searchPatterns)
            {
                try
                {
                    var files = source.EnumerateFiles(pattern, SearchOption.TopDirectoryOnly);
                    foreach (var file in files)
                    {
                        await CopySingleFileAsync(file, relativeDirPath, destination, isReverseCopy);
                    }
                }
                catch (Exception ex)
                {
                    LogMessage($"文件处理失败: {pattern} | 错误：{ex.Message}", true);
                }
            }
        }

        private async Task ProcessSubdirectoriesAsync(
            DirectoryInfo source,
            string relativeParentPath,
            string[] searchPatterns,
            IFileDestination destination,
            bool isReverseCopy,
            int currentDepth = 0)
        {
            if (checkBox23.Checked && currentDepth >= _maxDirectoryDepth)
            {
                LogMessage($"达到目录深度限制({_maxDirectoryDepth})，停止遍历: {source.FullName}", false);
                return;
            }

            foreach (var dir in source.EnumerateDirectories())
            {
                try
                {
                    if (SystemDirectories.Contains(dir.Name) ||
                        (dir.Attributes & (FileAttributes.System | FileAttributes.Hidden)) != 0)
                    {
                        LogMessage($"跳过系统目录：{dir.FullName}", false);
                        continue;
                    }

                    if (!PassFolderNameFilter(dir.Name))
                    {
                        LogMessage($"跳过不包含关键词的文件夹：{dir.FullName}", false);
                        continue;
                    }

                    _cts.Token.ThrowIfCancellationRequested();
                    string childRelative = string.IsNullOrEmpty(relativeParentPath)
                        ? dir.Name
                        : Path.Combine(relativeParentPath, dir.Name).Replace('\\', '/');
                    await CopyDirectoryAsync(dir, childRelative, searchPatterns, destination, isReverseCopy, currentDepth + 1);
                }
                catch (UnauthorizedAccessException)
                {
                    LogMessage($"目录访问被拒绝：{dir.FullName}", true);
                }
            }
        }

        private async Task CopySingleFileAsync(
            FileInfo file,
            string relativeDirPath,
            IFileDestination destination,
            bool isReverseCopy)
        {
            const int maxRetries = 3;
            int attempt = 0;
            TimeSpan delay = TimeSpan.FromSeconds(1);
            bool success = false;

            // 构建远程相对路径
            string relativeFilePath = string.IsNullOrEmpty(relativeDirPath)
                ? file.Name
                : Path.Combine(relativeDirPath, file.Name).Replace('\\', '/');

            if (ShouldSkipFile(file, isReverseCopy))
            {
                LogMessage($"跳过文件：{file.FullName}", false);
                return;
            }

            if (!PassFileNameFilter(file.Name))
            {
                LogMessage($"文件名不包含关键词：{file.FullName}", false);
                return;
            }

            if (checkBox11.Checked && ShouldSkipByFileSize(file))
            {
                Interlocked.Increment(ref _totalFiles);
                Interlocked.Increment(ref _failureCount);
                LogMessage($"文件过大已跳过：{file.FullName}", true);
                UpdateCountDisplay();
                return;
            }

            string driveId = GetDriveId(new DriveInfo(Path.GetPathRoot(file.FullName)));
            bool limitSpeed = ShouldLimitSpeed(driveId);
            int bufferSize = limitSpeed ? LimitedBufferSize : NormalBufferSize;
            int speedLimit = limitSpeed ? GetCurrentSpeedLimit() : int.MaxValue;

            if (limitSpeed && attempt == 0)
            {
                LogMessage($"限速模式复制：{file.FullName} (速度限制: {speedLimit / 1024 / 1024} MB/秒, 前{(int)numericUpDown1.Value}分钟)", false);
            }

            while (attempt <= maxRetries && !success)
            {
                try
                {
                    bool remoteExists = await destination.FileExistsAsync(relativeFilePath, _cts.Token);
                    DateTime? remoteLastWrite = null;
                    if (remoteExists)
                    {
                        try
                        {
                            remoteLastWrite = await destination.GetFileLastWriteTimeUtcAsync(relativeFilePath, _cts.Token);
                        }
                        catch (NotSupportedException) { /* 服务器不支持 Last-Modified，忽略 */ }
                        catch (FileNotFoundException) { remoteExists = false; }
                    }

                    var action = GetDuplicateFileAction();

                    if (remoteExists)
                    {
                        // 可选：检查文件内容是否相同（跳过相同的文件，节省时间）
                        // 这里不自动检查，只按用户选择的处理方式处理
                        switch (action)
                        {
                            case DuplicateFileAction.Skip:
                                LogMessage($"跳过已存在文件：{file.FullName}", false);
                                return;
                            case DuplicateFileAction.Overwrite:
                                await destination.DeleteFileAsync(relativeFilePath, _cts.Token);
                                remoteExists = false;
                                break;
                            case DuplicateFileAction.KeepBoth:
                                // 生成唯一文件名
                                string ext = Path.GetExtension(relativeFilePath);
                                string nameWithoutExt = relativeFilePath.Substring(0, relativeFilePath.Length - ext.Length);
                                int counter = 1;
                                string newPath;
                                do
                                {
                                    newPath = $"{nameWithoutExt} ({counter++}){ext}";
                                } while (await destination.FileExistsAsync(newPath, _cts.Token));
                                relativeFilePath = newPath;
                                break;
                            case DuplicateFileAction.ReplaceWithNewer:
                                if (remoteLastWrite.HasValue && file.LastWriteTimeUtc <= remoteLastWrite.Value)
                                {
                                    LogMessage($"远程文件版本较新或相同，跳过：{file.FullName}", false);
                                    return;
                                }
                                await destination.DeleteFileAsync(relativeFilePath, _cts.Token);
                                remoteExists = false;
                                break;
                        }
                    }

                    // 复制文件内容
                    using (var sourceStream = new FileStream(
                        file.FullName, FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize, FileOptions.Asynchronous))
                    {
                        if (limitSpeed)
                        {
                            await CopyWithSpeedLimitAsync(sourceStream, destination, relativeFilePath, speedLimit, bufferSize);
                        }
                        else
                        {
                            await destination.WriteFileAsync(relativeFilePath, sourceStream, _cts.Token);
                        }
                    }

                    LogMessage($"成功复制：{file.FullName} -> {relativeFilePath}", false);
                    Interlocked.Increment(ref _successCount);
                    success = true;
                }
                catch (Exception ex) when (IsTransientError(ex) && attempt < maxRetries)
                {
                    attempt++;
                    LogMessage($"复制失败（将重试 {attempt}/{maxRetries}）：{file.FullName} | 错误：{ex.Message}", true);
                    await Task.Delay(TimeSpan.FromSeconds(delay.TotalSeconds * attempt), _cts.Token);
                }
                catch (Exception ex)
                {
                    LogMessage($"复制失败：{file.FullName} | 错误：{ex.Message}", true);
                    Interlocked.Increment(ref _failureCount);
                    break;
                }
                finally
                {
                    if (attempt >= maxRetries || success)
                    {
                        Interlocked.Increment(ref _totalFiles);
                        UpdateCountDisplay();
                    }
                }
            }
        }

        /// <summary>
        /// 限速复制：通过节流 Stream 控制上传速率，避免缓冲整个文件
        /// </summary>
        private async Task CopyWithSpeedLimitAsync(Stream source, IFileDestination destination, string remotePath, int speedLimitBytesPerSecond, int bufferSize)
        {
            using (var throttled = new ThrottledStream(source, speedLimitBytesPerSecond))
            {
                await destination.WriteFileAsync(remotePath, throttled, _cts.Token);
            }
        }

        /// <summary>
        /// 限速流包装器：限制底层流的读取速率
        /// </summary>
        private sealed class ThrottledStream : Stream
        {
            private readonly Stream _inner;
            private readonly int _bytesPerSecond;
            private readonly Stopwatch _timer = new Stopwatch();
            private long _bytesThisSecond;

            public ThrottledStream(Stream inner, int bytesPerSecond)
            {
                _inner = inner;
                _bytesPerSecond = bytesPerSecond;
            }

            public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken ct)
            {
                int maxRead = Math.Min(count, _bytesPerSecond);
                if (!_timer.IsRunning) _timer.Restart();

                if (_bytesThisSecond >= _bytesPerSecond && _timer.ElapsedMilliseconds < 1000)
                {
                    int delay = 1000 - (int)_timer.ElapsedMilliseconds;
                    if (delay > 0) await Task.Delay(delay, ct);
                    _timer.Restart();
                    _bytesThisSecond = 0;
                }
                else if (_timer.ElapsedMilliseconds >= 1000)
                {
                    _timer.Restart();
                    _bytesThisSecond = 0;
                }

                int actualRead = await _inner.ReadAsync(buffer, offset, Math.Min(maxRead, count), ct);
                _bytesThisSecond += actualRead;
                return actualRead;
            }

            public override int Read(byte[] buffer, int offset, int count) => _inner.Read(buffer, offset, count);
            public override bool CanRead => true;
            public override bool CanSeek => false;
            public override bool CanWrite => false;
            public override long Length => throw new NotSupportedException();
            public override long Position { get => throw new NotSupportedException(); set => throw new NotSupportedException(); }
            public override void Flush() { }
            public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
            public override void SetLength(long value) => throw new NotSupportedException();
            public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();

            protected override void Dispose(bool disposing)
            {
                if (disposing) _inner.Dispose();
                base.Dispose(disposing);
            }
        }

        private bool ShouldSkipFile(FileInfo file, bool isReverseCopy)
        {
            if (SystemFiles.Contains(file.Name))
                return true;

            if (isReverseCopy && file.Name == _reverseCopyMarker)
                return true;

            if (!isReverseCopy && file.Name == _reverseCopyIndicator)
                return true;

            return (file.Attributes & (FileAttributes.System | FileAttributes.Hidden)) != 0;
        }

        private bool ShouldSkipByFileSize(FileInfo file)
        {
            if (!checkBox11.Checked) return false;

            if (!long.TryParse(textBox3.Text, out var maxSizeMB))
                return false;

            const long bytesPerMB = 1024 * 1024;
            long maxBytes = maxSizeMB * bytesPerMB;
            return file.Length > maxBytes;
        }

        private bool IsTransientError(Exception ex)
        {
            return ex is IOException ||
                   ex is UnauthorizedAccessException ||
                   (ex is OperationCanceledException && !_cts.IsCancellationRequested);
        }

        private DuplicateFileAction GetDuplicateFileAction()
        {
            if (radioButton1.Checked) return DuplicateFileAction.Skip;
            if (radioButton2.Checked) return DuplicateFileAction.Overwrite;
            if (radioButton3.Checked) return DuplicateFileAction.KeepBoth;
            if (radioButton4.Checked) return DuplicateFileAction.ReplaceWithNewer;
            return DuplicateFileAction.Skip;
        }

        private void UpdateCountDisplay()
        {
            int total = Interlocked.CompareExchange(ref _totalFiles, 0, 0);
            int success = Interlocked.CompareExchange(ref _successCount, 0, 0);
            int failure = Interlocked.CompareExchange(ref _failureCount, 0, 0);

            if (label4.InvokeRequired)
            {
                label4.BeginInvoke((Action)(() =>
                {
                    label4.Text = $"一共复制{total}文件，成功{success}个，失败{failure}个";
                }));
            }
            else
            {
                label4.Text = $"一共复制{total}文件，成功{success}个，失败{failure}个";
            }
        }

        private Task SafeInvokeAsync(Action action)
        {
            if (InvokeRequired)
                return Task.Factory.FromAsync(BeginInvoke(action), _ => { });
            else
            {
                action();
                return Task.CompletedTask;
            }
        }

        private string GetLogFilePath(IFileDestination destination)
        {
            // 本地模式：使用用户指定的目标目录
            if (destination is LocalFileDestination)
                return Path.Combine(textBox2.Text, "CopyLog.txt");

            // 远程模式：使用程序运行目录
            return Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "CopyLog.txt");
        }

        private bool ValidateTargetDirectory()
        {
            if (string.IsNullOrWhiteSpace(textBox2.Text))
            {
                LogMessage("错误：未选择目标目录", true);
                return false;
            }

            try
            {
                if (!Path.IsPathRooted(textBox2.Text))
                {
                    LogMessage("错误：目标路径必须是绝对路径", true);
                    return false;
                }

                var fullPath = Path.GetFullPath(textBox2.Text);
                if (fullPath.StartsWith(@"\\?\"))
                {
                    LogMessage("警告：长路径格式可能需要系统支持", true);
                }

                Directory.CreateDirectory(fullPath);
                textBox2.Text = fullPath;
                return true;
            }
            catch (Exception ex)
            {
                LogMessage($"目录验证失败：{ex.Message}", true);
                return false;
            }
        }

        private async Task RecordDirectoryTree(DriveInfo drive)
        {
            if (!_createDirectoryTree)
            {
                LogMessage($"文件树状图生成已禁用", false);
                return;
            }

            try
            {
                string driveId = GetDriveId(drive);
                string treeFilePath = Path.Combine(textBox2.Text, $"{SanitizeFolderName(drive.VolumeLabel ?? drive.Name.Replace(":\\", ""))}_目录树_{DateTime.Now:yyyyMMdd_HHmmss}.txt");

                await Task.Run(() =>
                {
                    using (var writer = new StreamWriter(treeFilePath, false, Encoding.UTF8))
                    {
                        writer.WriteLine($"U盘目录树 - {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
                        writer.WriteLine($"驱动器: {drive.Name}");
                        writer.WriteLine($"卷标: {drive.VolumeLabel ?? "无"}");
                        writer.WriteLine($"总空间: {drive.TotalSize / (1024 * 1024 * 1024.0):F2} GB");
                        writer.WriteLine($"可用空间: {drive.AvailableFreeSpace / (1024 * 1024 * 1024.0):F2} GB");
                        writer.WriteLine($"目录深度限制: {(checkBox23.Checked ? _maxDirectoryDepth.ToString() : "无限制")}");
                        writer.WriteLine();
                        writer.WriteLine("目录结构:");
                        writer.WriteLine();

                        WriteDirectoryTree(writer, drive.RootDirectory.FullName, 0);
                    }
                });

                LogMessage($"已生成目录树文件: {treeFilePath}", true);
            }
            catch (Exception ex)
            {
                LogMessage($"生成目录树失败: {ex.Message}", true);
            }
        }

        private void WriteDirectoryTree(StreamWriter writer, string path, int level)
        {
            if (level > _maxDirectoryDepth) return;

            try
            {
                string indent = new string(' ', level * 2);
                string dirName = Path.GetFileName(path);
                if (string.IsNullOrEmpty(dirName)) dirName = path;
                writer.WriteLine($"{indent}├── {dirName}/");

                if (_filterByFolderName && _folderNameKeywords.Count > 0)
                {
                    if (!_folderNameKeywords.Any(kw =>
                        dirName.IndexOf(kw, StringComparison.OrdinalIgnoreCase) >= 0))
                    {
                        return;
                    }
                }

                var directories = Directory.GetDirectories(path);
                foreach (var dir in directories)
                {
                    if (SystemDirectories.Contains(Path.GetFileName(dir)))
                        continue;
                    WriteDirectoryTree(writer, dir, level + 1);
                }

                var files = Directory.GetFiles(path);
                foreach (var file in files)
                {
                    if (SystemFiles.Contains(Path.GetFileName(file)))
                        continue;
                    var fileInfo = new FileInfo(file);
                    string fileName = Path.GetFileName(file);
                    writer.WriteLine($"{indent}│   ├── {fileName} ({fileInfo.Length / 1024.0:F1} KB)");
                }
            }
            catch (UnauthorizedAccessException)
            {
                writer.WriteLine($"{new string(' ', level * 2)}│   └── [访问被拒绝]");
            }
            catch (Exception ex)
            {
                writer.WriteLine($"{new string(' ', level * 2)}│   └── [错误: {ex.Message}]");
            }
        }

        private string CreateDriveFolderName(DriveInfo drive)
        {
            string volumeSerial = GetDriveId(drive);
            string folderName = SanitizeFolderName(
                !string.IsNullOrWhiteSpace(drive.VolumeLabel) ?
                $"{drive.VolumeLabel}_{volumeSerial}" :
                $"{drive.Name.Replace(":\\", "")}_{volumeSerial}");

            return folderName;
        }

        private string GetLocalBackupPath(DriveInfo drive)
        {
            string folderName = SanitizeFolderName(!string.IsNullOrWhiteSpace(drive.VolumeLabel)
                ? drive.VolumeLabel
                : $"{drive.Name.Replace(":\\", "")}_DRIVE");

            return Path.Combine(textBox2.Text, folderName);
        }

        private string SanitizeFolderName(string name)   // 此方法应该已经存在，若不存在请添加
        {
            if (string.IsNullOrWhiteSpace(name)) return "UNKNOWN_DRIVE";

            var invalidChars = Path.GetInvalidFileNameChars();
            var cleanName = new string(name
                .Where(c => !invalidChars.Contains(c) || c == '_' || c == '-')
                .ToArray())
                .Trim();

            var reservedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "CON", "PRN", "AUX", "NUL",
        "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
        "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9"
    };

            if (reservedNames.Contains(cleanName))
            {
                cleanName += "_DATA";
            }

            return cleanName.Length > 50
                ? $"{cleanName.Substring(0, 45)}~"
                : cleanName;
        }
    }
}
