// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using System.Collections.Generic;

namespace U盘文件复制
{
    partial class Form1
    {
        // 常量定义
        private const string AllFilesPattern = "*.*";
        private const int MaxLogLines = 900;
        private const int WH_KEYBOARD_LL = 13;
        private const int NormalBufferSize = 81920; // 80KB
        private const int LimitedBufferSize = 4096; // 4KB

        // 开机自启动常量
        private const string AutoStartRegistryKey = @"Software\Microsoft\Windows\CurrentVersion\Run";
        private const string AppName = "U盘文件复制器";

        // 特殊文件标记
        private string _reverseCopyIndicator = "copy.stop";
        private string _reverseCopyMarker = ".reverse_copied";

        // 系统目录和文件集合
        private static readonly HashSet<string> SystemDirectories = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "System Volume Information",
            "$RECYCLE.BIN",
            ".Trashes",
            ".Spotlight-V100",
            ".fseventsd",
            "Recovery"
        };

        private static readonly HashSet<string> SystemFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "desktop.ini",
            "thumbs.db",
            "autorun.inf"
        };

        // 文件扩展名定义
        private static readonly string[] PowerPointExtensions = { "*.ppt", "*.pptx" };
        private static readonly string[] WordExtensions = { "*.doc", "*.docx", "*.txt" };
        private static readonly string[] ExcelExtensions = { "*.xlsx", "*.xls" };
        private static readonly string[] PdfExtensions = { "*.pdf" };
        private static readonly string[] ImageExtensions = { "*.jpg", "*.jpeg", "*.png", "*.gif", "*.bmp", "*.webp" };
        private static readonly string[] VideoExtensions = { "*.mp4", "*.avi", "*.mov", "*.mkv", "*.wmv", "*.flv" };
        private static readonly string[] AudioExtensions = { "*.mp3", "*.wma", "*.wav", "*.ape", "*.ogg", "*.flac", "*.aac" };
        private static readonly string[] CompressedExtensions = { "*.zip", "*.rar", "*.7z", "*.tar", "*.gz", "*.bz2", "*.xz", "*.zst", "*.001", "*.iso", "*.wim", "*.cab" };

        // 枚举定义
        private enum DuplicateFileAction
        {
            Skip,
            Overwrite,
            KeepBoth,
            ReplaceWithNewer
        }

        private enum FileActionType
        {
            None,
            StopCopy,
            ReverseCopy
        }
    }
}
