// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System.Collections.Generic;
using System.Linq;

namespace U盘文件复制
{
    partial class Form1
    {
        /// <summary>
        /// 获取选中的文件扩展名
        /// </summary>
        private IEnumerable<string> GetSelectedExtensions()
        {
            if (checkBox8.Checked) return new[] { AllFilesPattern };

            var extensions = new List<string>();
            AddOfficeExtensions(extensions);
            AddMediaExtensions(extensions);
            AddCompressedExtensions(extensions);
            AddCustomExtensions(extensions);
            AddAudioExtension(extensions);
            return extensions;
        }

        private void AddOfficeExtensions(List<string> extensions)
        {
            if (checkBox1.Checked) extensions.AddRange(PowerPointExtensions);
            if (checkBox2.Checked) extensions.AddRange(WordExtensions);
            if (checkBox3.Checked) extensions.AddRange(ExcelExtensions);
            if (checkBox4.Checked) extensions.AddRange(PdfExtensions);
        }

        private void AddMediaExtensions(List<string> extensions)
        {
            if (checkBox5.Checked) extensions.AddRange(ImageExtensions);
            if (checkBox6.Checked) extensions.AddRange(VideoExtensions);
        }

        private void AddCompressedExtensions(List<string> extensions)
        {
            if (checkBox9.Checked) extensions.AddRange(CompressedExtensions);
        }

        private void AddCustomExtensions(List<string> extensions)
        {
            if (!checkBox7.Checked || string.IsNullOrWhiteSpace(textBox1.Text)) return;

            extensions.AddRange(
                textBox1.Text.Split(',')
                    .Select(ext => ext.Trim().TrimStart('.'))
                    .Where(ext => !string.IsNullOrWhiteSpace(ext))
                    .Select(ext => $"*.{ext}")
            );
        }

        private void AddAudioExtension(List<string> extensions)
        {
            if (checkBox10.Checked) extensions.AddRange(AudioExtensions);
        }
    }
}
