// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace U盘文件复制
{
    partial class Form1
    {
        // 日志相关字段
        private readonly StringBuilder _logBuffer = new StringBuilder();
        private int _currentLogLines = 0;
        private bool _logSuccess = true;
        private bool _logErrors = true;
        private bool _logNeutral = true;
        private bool _saveLogToFile = true;
        private bool _showLogInWindow = true;

        /// <summary>
        /// 设置日志控件
        /// </summary>
        private void SetupLogSettingsControls()
        {
            checkBox16.CheckedChanged += (s, e) => _logSuccess = checkBox16.Checked;
            checkBox17.CheckedChanged += (s, e) => _logErrors = checkBox17.Checked;
            checkBox18.CheckedChanged += (s, e) => _logNeutral = checkBox18.Checked;
            checkBox19.CheckedChanged += (s, e) => _saveLogToFile = checkBox19.Checked;
            checkBox20.CheckedChanged += (s, e) => _showLogInWindow = checkBox20.Checked;
        }

        /// <summary>
        /// 记录日志消息
        /// </summary>
        private void LogMessage(string message, bool isError = false)
        {
            try
            {
                if (!ShouldLogMessage(message, isError))
                    return;

                var logEntry = $"[{DateTime.Now:HH:mm:ss}] {message}";

                if (_showLogInWindow)
                {
                    UpdateLogBuffer(logEntry);
                    UpdateLogDisplay(logEntry);
                }

                if (_saveLogToFile)
                {
                    WriteToLogFile(logEntry);
                }
            }
            catch (Exception ex)
            {
                var errorMessage = $"[{DateTime.Now:HH:mm:ss}] 日志记录失败: {ex.Message}";
                try
                {
                    if (richTextBox1.InvokeRequired)
                    {
                        richTextBox1.BeginInvoke((Action)(() =>
                            richTextBox1.AppendText(errorMessage + Environment.NewLine)));
                    }
                    else
                    {
                        richTextBox1.AppendText(errorMessage + Environment.NewLine);
                    }
                }
                catch { }
            }
        }

        private bool ShouldLogMessage(string message, bool isError)
        {
            if (isError && !_logErrors)
                return false;

            if (!isError)
            {
                if (message.Contains("成功") && !_logSuccess)
                    return false;

                if (!message.Contains("成功") && !_logNeutral)
                    return false;
            }

            return true;
        }

        private void UpdateLogBuffer(string entry)
        {
            lock (_logBuffer)
            {
                _logBuffer.AppendLine(entry);
                _currentLogLines++;

                if (_currentLogLines > MaxLogLines)
                {
                    // 截断最早的日志行，保留最后 MaxLogLines 行
                    var full = _logBuffer.ToString();
                    var newlineIdx = full.IndexOf('\n');
                    if (newlineIdx >= 0)
                    {
                        _logBuffer.Clear();
                        _logBuffer.Append(full.Substring(newlineIdx + 1));
                    }
                    _currentLogLines = MaxLogLines;
                }
            }
        }

        private void UpdateLogDisplay(string entry)
        {
            if (richTextBox1.InvokeRequired)
            {
                richTextBox1.BeginInvoke((Action)(() =>
                {
                    richTextBox1.AppendText(entry + Environment.NewLine);
                    richTextBox1.ScrollToCaret();
                }));
                return;
            }

            richTextBox1.AppendText(entry + Environment.NewLine);
            richTextBox1.ScrollToCaret();
        }

        private void WriteToLogFile(string entry)
        {
            try
            {
                if (!string.IsNullOrEmpty(_logPath))
                {
                    File.AppendAllText(_logPath, entry + Environment.NewLine);
                }
            }
            catch (Exception ex)
            {
                var errorMessage = $"[{DateTime.Now:HH:mm:ss}] 日志文件写入失败: {ex.Message}";
                _ = SafeInvokeAsync(() => richTextBox1.AppendText(errorMessage + Environment.NewLine));

                try
                {
                    string backupLog = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "CopyLog.txt");
                    File.AppendAllText(backupLog, errorMessage + Environment.NewLine);
                }
                catch { }
            }
        }
    }
}
