// Form1.UIControls.cs
// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace U盘文件复制
{
    partial class Form1
    {

        /// <summary>
        /// 设置UI控件
        /// </summary>
        private void SetupControls()
        {
            checkBox8.CheckedChanged += (_, __) =>
            {
                textBox1.Enabled = !checkBox8.Checked;
                ToggleAllCheckboxes(checkBox8.Checked);
            };
            textBox1.Enabled = !checkBox8.Checked;

            // 新增：绑定服务器配置界面事件
            SetupServerConfigControls();
        }

        /// <summary>
        /// 设置服务器配置相关控件
        /// </summary>
        private void SetupServerConfigControls()
        {
            // 绑定"浏览远程目录"按钮事件
            _btnBrowseRemote.Click += async (s, e) => await BrowseRemoteDirectory();

            // 文件保存位置切换：启用/禁用服务器配置组
            radioButton5.CheckedChanged += (s, e) =>
            {
                groupBox11.Enabled = false;
                button3.Enabled = false;
                _btnBrowseRemote.Enabled = false;
                SaveSettings();
                // 切换后重新创建目标
                _currentDestination = CreateFileDestination();
            };
            radioButton6.CheckedChanged += (s, e) =>
            {
                groupBox11.Enabled = true;
                button3.Enabled = true;
                _btnBrowseRemote.Enabled = true;
                SaveSettings();
                _currentDestination = CreateFileDestination();
            };
            // 初始状态
            groupBox11.Enabled = radioButton6.Checked;
            button3.Enabled = radioButton6.Checked;
            _btnBrowseRemote.Enabled = radioButton6.Checked;

            // 测试连接按钮
            button3.Click += async (s, e) => await TestServerConnection();

            // 任何配置项改变时自动保存并重建目标（可选，但建议）
            textBox8.TextChanged += (s, e) => { SaveSettings(); _currentDestination = CreateFileDestination(); };
            textBox9.TextChanged += (s, e) => { SaveSettings(); _currentDestination = CreateFileDestination(); };
            textBox10.TextChanged += (s, e) => { SaveSettings(); _currentDestination = CreateFileDestination(); };
            textBox11.TextChanged += (s, e) => { SaveSettings(); _currentDestination = CreateFileDestination(); };
            checkBox26.CheckedChanged += (s, e) => { SaveSettings(); _currentDestination = CreateFileDestination(); };
            checkBox27.CheckedChanged += (s, e) => { SaveSettings(); _currentDestination = CreateFileDestination(); };
            textBox12.TextChanged += (s, e) => { SaveSettings(); _currentDestination = CreateFileDestination(); };
            comboBox1.SelectedIndexChanged += (s, e) => { SaveSettings(); _currentDestination = CreateFileDestination(); };
        }

        /// <summary>
        /// 测试服务器连接
        /// </summary>
        private async Task TestServerConnection()
        {
            if (!radioButton6.Checked)
            {
                label21.Text = "未启用服务器模式";
                return;
            }

            // 构建配置
            var config = BuildServerConfigFromUi();
            if (config == null)
            {
                label21.Text = "配置无效";
                return;
            }

            button3.Enabled = false;
            label21.Text = "测试中...";
            try
            {
                // 注意：NetworkHelper.TestConnectionAsync 将在任务4中实现
                bool success = await NetworkHelper.TestConnectionAsync(config);
                label21.Text = success ? "连接成功" : "连接失败，请检查配置";
            }
            catch (Exception ex)
            {
                label21.Text = $"错误: {ex.Message}";
            }
            finally
            {
                button3.Enabled = true;
            }
        }

        /// <summary>
        /// 从UI控件构建 ServerConfig 对象
        /// </summary>
        private ServerConfig BuildServerConfigFromUi()
        {
            if (string.IsNullOrWhiteSpace(textBox8.Text))
            {
                LogMessage("服务器地址不能为空", true);
                return null;
            }
            if (!int.TryParse(textBox11.Text, out int port) || port < 1 || port > 65535)
                port = 443;

            // 解析分块大小（单位：KB/MB）
            int chunkSizeValue = int.TryParse(textBox12.Text, out int val) ? val : 1;
            string unit = comboBox1.SelectedItem?.ToString() ?? "MB";
            int chunkSizeBytes = unit == "MB" ? chunkSizeValue * 1024 * 1024 : chunkSizeValue * 1024;

            return new ServerConfig
            {
                ServerAddress = textBox8.Text.Trim(),
                Port = port,
                UseHttps = checkBox26.Checked,
                Password = textBox9.Text,
                ApiToken = textBox10.Text,
                RemoteRootPath = "/",
                ValidateCertificate = true,
                TimeoutSeconds = 30,
                ChunkSizeBytes = chunkSizeBytes,
                MaxRetries = 3
            };
        }

        /// <summary>
        /// 根据当前UI选择创建对应的文件存储目标
        /// </summary>
        private IFileDestination CreateFileDestination()
        {
            if (radioButton6.Checked) // 服务器
            {
                var config = BuildServerConfigFromUi();
                if (config == null)
                {
                    LogMessage("服务器配置无效，回退到本地存储。", true);
                    return new LocalFileDestination(GetDefaultLocalPath());
                }
                bool useChunked = checkBox27.Checked;
                return new HttpFileDestination(config, useChunked);
            }
            else
            {
                // 本地模式：如果目标目录为空，使用默认路径
                string localPath = string.IsNullOrWhiteSpace(textBox2.Text)
                    ? GetDefaultLocalPath()
                    : textBox2.Text;
                return new LocalFileDestination(localPath);
            }
        }

        private string GetDefaultLocalPath()
        {
            // 默认保存到桌面下的 "U盘文件备份" 文件夹
            string desktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            string defaultPath = Path.Combine(desktop, "U盘文件备份");
            return defaultPath;
        }

        /// <summary>
        /// 设置复选框事件
        /// </summary>
        private void SetupCheckboxEvents()
        {
            var checkBoxes = new[] { checkBox1, checkBox2, checkBox3, checkBox4, checkBox5, checkBox6, checkBox7, checkBox9, checkBox10 };
            foreach (var cb in checkBoxes)
            {
                cb.CheckedChanged += SyncCheckBoxStates;
            }
        }

        private void SyncCheckBoxStates(object sender, EventArgs e)
        {
            var checkBoxes = new[] { checkBox1, checkBox2, checkBox3, checkBox4, checkBox5, checkBox6, checkBox7, checkBox9, checkBox10 };
            checkBox8.Checked = checkBoxes.All(cb => cb.Checked);
        }

        private void CheckBox8_CheckedChanged(object sender, EventArgs e)
        {
            ToggleAllCheckboxes(checkBox8.Checked);
        }

        private void ToggleAllCheckboxes(bool state)
        {
            var checkBoxes = new[] { checkBox1, checkBox2, checkBox3, checkBox4, checkBox5, checkBox6, checkBox7, checkBox9, checkBox10 };

            foreach (var cb in checkBoxes)
            {
                cb.CheckedChanged -= SyncCheckBoxStates;
            }

            foreach (var cb in checkBoxes)
            {
                cb.Checked = state;
            }

            foreach (var cb in checkBoxes)
            {
                cb.CheckedChanged += SyncCheckBoxStates;
            }

            textBox1.Enabled = !state;
        }

        private void SetupDuplicateFileHandling()
        {
            radioButton1.Checked = true;
        }

        private void SetupSpeedLimitControls()
        {
            checkBox13.CheckedChanged += (s, e) =>
            {
                numericUpDown1.Enabled = checkBox13.Checked;
                comboBoxSpeed.Enabled = checkBox13.Checked;
                if (!checkBox13.Checked)
                {
                    numericUpDown1.Value = 5;
                    comboBoxSpeed.SelectedIndex = 1;
                }
            };

            comboBoxSpeed.SelectedIndex = 1;
            comboBoxSpeed.Enabled = checkBox13.Checked;
            numericUpDown1.Enabled = checkBox13.Checked;

            comboBoxSpeed.SelectedIndexChanged += (s, e) => UpdateSpeedLimit();
        }

        private void UpdateSpeedLimit()
        {
            if (comboBoxSpeed.SelectedItem == null) return;

            string selectedSpeed = comboBoxSpeed.SelectedItem.ToString();

            switch (selectedSpeed)
            {
                case "1 MB/秒":
                    _currentSpeedLimit = 1 * 1024 * 1024;
                    break;
                case "2 MB/秒":
                    _currentSpeedLimit = 2 * 1024 * 1024;
                    break;
                case "5 MB/秒":
                    _currentSpeedLimit = 5 * 1024 * 1024;
                    break;
                case "10 MB/秒":
                    _currentSpeedLimit = 10 * 1024 * 1024;
                    break;
                default:
                    _currentSpeedLimit = 2 * 1024 * 1024;
                    break;
            }
        }

        private void SetDefaultValues()
        {
            // 设置默认本地保存目录（桌面/U盘文件备份）
            if (string.IsNullOrWhiteSpace(textBox2.Text))
            {
                string defaultPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "U盘文件备份");
                textBox2.Text = defaultPath;
            }

            // 目录深度设置
            checkBox22.Checked = true;
            checkBox23.Checked = false;
            numericUpDown2.Value = 3;
            numericUpDown2.Enabled = false;

            // 日志设置
            checkBox16.Checked = true;
            checkBox17.Checked = true;
            checkBox18.Checked = true;
            checkBox19.Checked = true;
            checkBox20.Checked = true;

            // U盘特殊设置
            checkBox14.Checked = false;
            checkBox15.Checked = false;
            textBox5.Text = "stop.copy";
            textBox6.Text = "reverse.copy";
            textBox5.Enabled = false;
            textBox6.Enabled = false;

            // 文件夹名称过滤
            checkBox21.Checked = false;
            textBox7.Enabled = false;

            // 服务器配置默认值
            if (textBox11 != null) textBox11.Text = "443";
            if (checkBox26 != null) checkBox26.Checked = true;
            if (checkBox27 != null) checkBox27.Checked = false;   // 默认不分块
            if (textBox12 != null) textBox12.Text = "1";
            if (comboBox1 != null) comboBox1.SelectedItem = "MB";

            // 初始化字段值
            _maxDirectoryDepth = int.MaxValue;
            _createDirectoryTree = true;
            _logSuccess = true;
            _logErrors = true;
            _logNeutral = true;
            _saveLogToFile = true;
            _showLogInWindow = true;
            _stopCopyWhenFileExists = false;
            _reverseCopyWhenFileExists = false;
            _stopCopyFileName = "stop.copy";
            _reverseCopyFileName = "reverse.copy";
            _filterByFolderName = false;
        }

        protected override void OnFormClosing(FormClosingEventArgs e)
        {
            SaveSettings();
            _cts?.Cancel();
            _ = CleanupResourcesAsync();
            base.OnFormClosing(e);
        }

        private async Task CleanupResourcesAsync()
        {
            try
            {
                await Task.Delay(500);
                _usbWatcher?.Stop();
                _usbWatcher?.Dispose();
                if (_hookID != IntPtr.Zero)
                {
                    UnhookWindowsHookEx(_hookID);
                    _hookID = IntPtr.Zero;
                }
                _cts?.Cancel();
                _cts?.Dispose();
                _copyLock?.Dispose();
            }
            catch { }
        }

        private void Button2_Click(object sender, EventArgs e)
        {
            using (var fbd = new FolderBrowserDialog())
            {
                if (fbd.ShowDialog() == DialogResult.OK)
                {
                    textBox2.Text = fbd.SelectedPath;
                    // 本地目录变化时，如果是本地模式需要重建目标（不过本地目标不需要重建，因为路径变了）
                    if (radioButton5.Checked)
                        _currentDestination = CreateFileDestination();
                }
            }
        }

        private void Button1_Click_1(object sender, EventArgs e)
        {
            this.Hide();
            this.ShowInTaskbar = false;
        }

        private void linkLabel1_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
        {
            try
            {
                Process.Start(new ProcessStartInfo
                {
                    FileName = "https://github.com/example/usb-file-copy",
                    UseShellExecute = true
                });
            }
            catch { }
        }

        /// <summary>
        /// 浏览远程服务器目录
        /// </summary>
        private async Task BrowseRemoteDirectory()
        {
            if (!radioButton6.Checked)
            {
                MessageBox.Show("请先切换到服务器模式", "提示", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            var config = BuildServerConfigFromUi();
            if (config == null) return;

            // 先测试连接
            label21.Text = "测试连接中...";
            bool connected = false;
            try
            {
                connected = await NetworkHelper.TestConnectionAsync(config);
            }
            catch { }

            if (!connected)
            {
                label21.Text = "连接失败";
                MessageBox.Show("服务器连接失败，请检查配置。", "连接失败", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            label21.Text = "已连接";
            try
            {
                var destination = new HttpFileDestination(config, checkBox27.Checked);
                using (var browser = new RemoteBrowserForm(destination))
                {
                    browser.ShowDialog(this);
                }
            }
            catch (Exception ex)
            {
                LogMessage($"浏览远程目录出错: {ex.Message}", true);
                label21.Text = $"错误: {ex.Message}";
            }
        }

        private void linkLabel2_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
        {
            try
            {
                Process.Start(new ProcessStartInfo
                {
                    FileName = "https://space.bilibili.com/example",
                    UseShellExecute = true
                });
            }
            catch { }
        }
    }
}