// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Windows.Forms;

namespace U盘文件复制
{
    partial class Form1
    {
        // 键盘钩子相关字段
        private IntPtr _hookID = IntPtr.Zero;
        private delegate IntPtr LowLevelKeyboardProc(int nCode, IntPtr wParam, IntPtr lParam);
        private LowLevelKeyboardProc _proc;
        private readonly Queue<Keys> _keySequence = new Queue<Keys>(3);
        private int _escPressCount;
        private DateTime _firstEscPress;

        // Windows API 导入
        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern IntPtr SetWindowsHookEx(int idHook, LowLevelKeyboardProc lpfn, IntPtr hMod, uint dwThreadId);

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool UnhookWindowsHookEx(IntPtr hhk);

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern IntPtr CallNextHookEx(IntPtr hhk, int nCode, IntPtr wParam, IntPtr lParam);

        [DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern IntPtr GetModuleHandle(string lpModuleName);

        /// <summary>
        /// 初始化键盘钩子
        /// </summary>
        private void InitializeKeyboardHook()
        {
            _proc = HookCallback;
            _hookID = SetHook(_proc);
        }

        private IntPtr SetHook(LowLevelKeyboardProc proc)
        {
            using (var curModule = Process.GetCurrentProcess().MainModule)
            {
                return SetWindowsHookEx(WH_KEYBOARD_LL, proc, GetModuleHandle(curModule.ModuleName), 0);
            }
        }

        private IntPtr HookCallback(int nCode, IntPtr wParam, IntPtr lParam)
        {
            if (nCode >= 0)
            {
                int vkCode = Marshal.ReadInt32(lParam);
                var key = (Keys)vkCode;

                if (wParam == (IntPtr)0x0100) // WM_KEYDOWN
                {
                    this.BeginInvoke((Action)(() => HandleKeyDown(key)));
                }
            }
            return CallNextHookEx(_hookID, nCode, wParam, lParam);
        }

        private void HandleKeyDown(Keys key)
        {
            // 检测 U+S+B 快捷键显示窗口
            if (key == Keys.U || key == Keys.S || key == Keys.B)
            {
                _keySequence.Enqueue(key);
                if (_keySequence.Count > 3) _keySequence.Dequeue();

                if (_keySequence.Count == 3 &&
                    _keySequence.ElementAt(0) == Keys.U &&
                    _keySequence.ElementAt(1) == Keys.S &&
                    _keySequence.ElementAt(2) == Keys.B)
                {
                    ShowMainWindow();
                    _keySequence.Clear();
                }
            }

            // 检测连按5次ESC退出程序
            if (key == Keys.Escape)
            {
                if (_escPressCount == 0)
                    _firstEscPress = DateTime.Now;

                _escPressCount++;

                if (_escPressCount >= 5 &&
                    (DateTime.Now - _firstEscPress).TotalSeconds <= 3)
                {
                    ExitApplication();
                }
                else if ((DateTime.Now - _firstEscPress).TotalSeconds > 3)
                {
                    _escPressCount = 0;
                }
            }
            else
            {
                _escPressCount = 0;
            }
        }

        /// <summary>
        /// 显示主窗口
        /// </summary>
        private void ShowMainWindow()
        {
            this.Show();
            this.WindowState = FormWindowState.Normal;
            this.ShowInTaskbar = true;
            this.BringToFront();
        }

        /// <summary>
        /// 退出应用程序
        /// </summary>
        private void ExitApplication()
        {
            if (_hookID != IntPtr.Zero)
                UnhookWindowsHookEx(_hookID);
            Application.Exit();
        }
    }
}
