// Form1.Settings.cs
// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Windows.Forms;
using System.Xml.Serialization;

namespace U盘文件复制
{
    partial class Form1
    {
        private static readonly string SettingsFilePath = Path.Combine(
            Application.StartupPath, "settings.xml");

        // 用于加密/解密的额外熵（可自定义）
        private static readonly byte[] Entropy = Encoding.UTF8.GetBytes("U盘文件复制器_SALT_2024");

        /// <summary>
        /// 应用程序设置类
        /// </summary>
        public class AppSettings
        {
            // 目标目录
            public string TargetDirectory { get; set; }

            // 文件类型选择
            public bool CopyPpt { get; set; } = true;
            public bool CopyWord { get; set; } = true;
            public bool CopyExcel { get; set; } = true;
            public bool CopyPdf { get; set; } = true;
            public bool CopyImage { get; set; } = true;
            public bool CopyVideo { get; set; } = true;
            public bool CopyAudio { get; set; } = true;
            public bool CopyCompressed { get; set; } = true;
            public bool CopyAllFiles { get; set; }
            public bool UseCustomExtensions { get; set; }
            public string CustomExtensions { get; set; }

            // 重复文件处理
            public int DuplicateFileAction { get; set; } = 0;

            // 文件大小限制
            public bool EnableFileSizeLimit { get; set; }
            public long MaxFileSizeMB { get; set; } = 100;

            // 文件名过滤
            public bool EnableFileNameFilter { get; set; }
            public string FileNameKeywords { get; set; }

            // 文件夹过滤
            public bool EnableFolderNameFilter { get; set; }
            public string FolderNameKeywords { get; set; }

            // 目录深度
            public bool CreateDirectoryTree { get; set; } = true;
            public bool LimitDirectoryDepth { get; set; }
            public int MaxDirectoryDepth { get; set; } = 3;

            // 日志设置
            public bool LogSuccess { get; set; } = true;
            public bool LogErrors { get; set; } = true;
            public bool LogNeutral { get; set; } = true;
            public bool SaveLogToFile { get; set; } = true;
            public bool ShowLogInWindow { get; set; } = true;

            // USB特殊文件
            public bool EnableStopCopyFile { get; set; }
            public string StopCopyFileName { get; set; } = "stop.copy";
            public bool EnableReverseCopyFile { get; set; }
            public string ReverseCopyFileName { get; set; } = "reverse.copy";

            // 速度限制
            public bool EnableSpeedLimit { get; set; }
            public int SpeedLimitMinutes { get; set; } = 5;
            public int SpeedLimitIndex { get; set; } = 1;

            // 开机自启动
            public bool AutoStart { get; set; }
            public bool AutoStartHidden { get; set; }

            // ===== 新增：服务器配置 =====
            public ServerConfig Server { get; set; } = new ServerConfig();

            // 保存位置：0=本地，1=服务器
            public int SaveLocation { get; set; } = 0;

            // 是否启用分块上传（大文件分块）
            public bool UseChunkedUpload { get; set; } = true;
        }

        /// <summary>
        /// 保存设置到文件（加密敏感信息）
        /// </summary>
        private void SaveSettings()
        {
            try
            {
                var settings = new AppSettings
                {
                    TargetDirectory = textBox2.Text,

                    // 文件类型
                    CopyPpt = checkBox1.Checked,
                    CopyWord = checkBox2.Checked,
                    CopyExcel = checkBox3.Checked,
                    CopyPdf = checkBox4.Checked,
                    CopyImage = checkBox5.Checked,
                    CopyVideo = checkBox6.Checked,
                    CopyAudio = checkBox10.Checked,
                    CopyCompressed = checkBox9.Checked,
                    CopyAllFiles = checkBox8.Checked,
                    UseCustomExtensions = checkBox7.Checked,
                    CustomExtensions = textBox1.Text,

                    // 重复文件处理
                    DuplicateFileAction = radioButton1.Checked ? 0 :
                                          radioButton2.Checked ? 1 :
                                          radioButton3.Checked ? 2 : 3,

                    // 文件大小限制
                    EnableFileSizeLimit = checkBox11.Checked,
                    MaxFileSizeMB = long.TryParse(textBox3.Text, out var size) ? size : 100,

                    // 文件名过滤
                    EnableFileNameFilter = checkBox12.Checked,
                    FileNameKeywords = textBox4.Text,

                    // 文件夹过滤
                    EnableFolderNameFilter = checkBox21.Checked,
                    FolderNameKeywords = textBox7.Text,

                    // 目录深度
                    CreateDirectoryTree = checkBox22.Checked,
                    LimitDirectoryDepth = checkBox23.Checked,
                    MaxDirectoryDepth = (int)numericUpDown2.Value,

                    // 日志设置
                    LogSuccess = checkBox16.Checked,
                    LogErrors = checkBox17.Checked,
                    LogNeutral = checkBox18.Checked,
                    SaveLogToFile = checkBox19.Checked,
                    ShowLogInWindow = checkBox20.Checked,

                    // USB特殊文件
                    EnableStopCopyFile = checkBox14.Checked,
                    StopCopyFileName = textBox5.Text,
                    EnableReverseCopyFile = checkBox15.Checked,
                    ReverseCopyFileName = textBox6.Text,

                    // 速度限制
                    EnableSpeedLimit = checkBox13.Checked,
                    SpeedLimitMinutes = (int)numericUpDown1.Value,
                    SpeedLimitIndex = comboBoxSpeed.SelectedIndex,

                    // 开机自启动
                    AutoStart = checkBox24.Checked,
                    AutoStartHidden = checkBox25.Checked,

                    // ===== 新增：服务器相关 =====
                    SaveLocation = radioButton5.Checked ? 0 : 1,
                    UseChunkedUpload = true,   // 可后续增加复选框控制，默认 true
                    Server = new ServerConfig
                    {
                        ServerAddress = textBox8.Text,
                        Port = int.TryParse(textBox11?.Text, out int port) ? port : 443,
                        UseHttps = checkBox26?.Checked ?? true,
                        Password = EncryptString(textBox9.Text),     // 加密存储
                        ApiToken = EncryptString(textBox10.Text),    // 加密存储
                        RemoteRootPath = "/",
                        ValidateCertificate = true,
                        TimeoutSeconds = 30,
                        ChunkSizeBytes = ParseChunkSize(),
                        MaxRetries = 3
                    }
                };

                var directory = Path.GetDirectoryName(SettingsFilePath);
                if (!Directory.Exists(directory))
                    Directory.CreateDirectory(directory);

                var serializer = new XmlSerializer(typeof(AppSettings));
                using (var writer = new StreamWriter(SettingsFilePath, false, Encoding.UTF8))
                {
                    serializer.Serialize(writer, settings);
                }
            }
            catch (Exception ex)
            {
                LogMessage($"保存设置失败: {ex.Message}", true);
            }
        }

        /// <summary>
        /// 加载设置
        /// </summary>
        private void LoadSettings()
        {
            try
            {
                if (!File.Exists(SettingsFilePath))
                {
                    // 首次运行，设置默认分块大小等（已在控件的默认值中设置）
                    return;
                }

                var serializer = new XmlSerializer(typeof(AppSettings));
                AppSettings settings;
                using (var reader = new StreamReader(SettingsFilePath, Encoding.UTF8))
                {
                    settings = (AppSettings)serializer.Deserialize(reader);
                }

                if (settings == null) return;

                // 目标目录
                textBox2.Text = settings.TargetDirectory ?? "";

                // 文件类型
                checkBox1.Checked = settings.CopyPpt;
                checkBox2.Checked = settings.CopyWord;
                checkBox3.Checked = settings.CopyExcel;
                checkBox4.Checked = settings.CopyPdf;
                checkBox5.Checked = settings.CopyImage;
                checkBox6.Checked = settings.CopyVideo;
                checkBox10.Checked = settings.CopyAudio;
                checkBox9.Checked = settings.CopyCompressed;
                checkBox8.Checked = settings.CopyAllFiles;
                checkBox7.Checked = settings.UseCustomExtensions;
                textBox1.Text = settings.CustomExtensions ?? "";

                // 重复文件处理
                switch (settings.DuplicateFileAction)
                {
                    case 0: radioButton1.Checked = true; break;
                    case 1: radioButton2.Checked = true; break;
                    case 2: radioButton3.Checked = true; break;
                    case 3: radioButton4.Checked = true; break;
                }

                // 文件大小限制
                checkBox11.Checked = settings.EnableFileSizeLimit;
                textBox3.Text = settings.MaxFileSizeMB.ToString();

                // 文件名过滤
                checkBox12.Checked = settings.EnableFileNameFilter;
                textBox4.Text = settings.FileNameKeywords ?? "";

                // 文件夹过滤
                checkBox21.Checked = settings.EnableFolderNameFilter;
                textBox7.Text = settings.FolderNameKeywords ?? "";

                // 目录深度
                checkBox22.Checked = settings.CreateDirectoryTree;
                checkBox23.Checked = settings.LimitDirectoryDepth;
                numericUpDown2.Value = settings.MaxDirectoryDepth;

                // 日志设置
                checkBox16.Checked = settings.LogSuccess;
                checkBox17.Checked = settings.LogErrors;
                checkBox18.Checked = settings.LogNeutral;
                checkBox19.Checked = settings.SaveLogToFile;
                checkBox20.Checked = settings.ShowLogInWindow;

                // USB特殊文件
                checkBox14.Checked = settings.EnableStopCopyFile;
                textBox5.Text = settings.StopCopyFileName;
                checkBox15.Checked = settings.EnableReverseCopyFile;
                textBox6.Text = settings.ReverseCopyFileName;

                // 速度限制
                checkBox13.Checked = settings.EnableSpeedLimit;
                numericUpDown1.Value = settings.SpeedLimitMinutes;
                comboBoxSpeed.SelectedIndex = settings.SpeedLimitIndex >= 0 ? settings.SpeedLimitIndex : 1;

                // 开机自启动
                checkBox24.Checked = settings.AutoStart;
                checkBox25.Checked = settings.AutoStartHidden;

                // ===== 新增：服务器相关 =====
                if (settings.Server != null)
                {
                    textBox8.Text = settings.Server.ServerAddress ?? "";
                    if (textBox11 != null) textBox11.Text = settings.Server.Port.ToString();
                    if (checkBox26 != null) checkBox26.Checked = settings.Server.UseHttps;
                    textBox9.Text = DecryptString(settings.Server.Password);
                    textBox10.Text = DecryptString(settings.Server.ApiToken);
                    // 分块大小恢复（需要将字节转换为 KB/MB）
                    RestoreChunkSizeUI(settings.Server.ChunkSizeBytes);
                }

                // 保存位置
                if (settings.SaveLocation == 0)
                    radioButton5.Checked = true;
                else
                    radioButton6.Checked = true;

                // 同步内部字段
                ApplySettingsToFields(settings);
            }
            catch (Exception ex)
            {
                LogMessage($"加载设置失败: {ex.Message}", true);
            }
        }

        // ===== 加密辅助方法 =====
        private static string EncryptString(string plainText)
        {
            if (string.IsNullOrEmpty(plainText)) return "";
            byte[] plainBytes = Encoding.UTF8.GetBytes(plainText);
            byte[] encryptedBytes = ProtectedData.Protect(plainBytes, Entropy, DataProtectionScope.CurrentUser);
            return Convert.ToBase64String(encryptedBytes);
        }

        private static string DecryptString(string encryptedBase64)
        {
            if (string.IsNullOrEmpty(encryptedBase64)) return "";
            byte[] encryptedBytes = Convert.FromBase64String(encryptedBase64);
            byte[] plainBytes = ProtectedData.Unprotect(encryptedBytes, Entropy, DataProtectionScope.CurrentUser);
            return Encoding.UTF8.GetString(plainBytes);
        }

        // ===== 分块大小序列化辅助 =====
        private int ParseChunkSize()
        {
            if (!int.TryParse(textBox12?.Text, out int val) || val <= 0) val = 1;
            string unit = comboBox1?.SelectedItem?.ToString() ?? "MB";
            if (unit == "MB")
                return val * 1024 * 1024;
            else
                return val * 1024;
        }

        private void RestoreChunkSizeUI(int chunkSizeBytes)
        {
            if (textBox12 == null || comboBox1 == null) return;
            if (chunkSizeBytes >= 1024 * 1024)
            {
                textBox12.Text = (chunkSizeBytes / (1024 * 1024)).ToString();
                comboBox1.SelectedItem = "MB";
            }
            else
            {
                textBox12.Text = (chunkSizeBytes / 1024).ToString();
                comboBox1.SelectedItem = "KB";
            }
        }

        private void ApplySettingsToFields(AppSettings settings)
        {
            _createDirectoryTree = settings.CreateDirectoryTree;
            _maxDirectoryDepth = settings.LimitDirectoryDepth ? settings.MaxDirectoryDepth : int.MaxValue;
            _logSuccess = settings.LogSuccess;
            _logErrors = settings.LogErrors;
            _logNeutral = settings.LogNeutral;
            _saveLogToFile = settings.SaveLogToFile;
            _showLogInWindow = settings.ShowLogInWindow;
            _stopCopyWhenFileExists = settings.EnableStopCopyFile;
            _reverseCopyWhenFileExists = settings.EnableReverseCopyFile;
            _stopCopyFileName = settings.StopCopyFileName;
            _reverseCopyFileName = settings.ReverseCopyFileName;
            _filterByFolderName = settings.EnableFolderNameFilter;
        }
    }
}