// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace U盘文件复制
{
    partial class Form1
    {
        // 文件过滤相关字段
        private readonly List<string> _fileNameKeywords = new List<string>();
        private readonly List<string> _folderNameKeywords = new List<string>();
        private bool _filterByFolderName = false;
        private int _maxDirectoryDepth = int.MaxValue;
        private bool _createDirectoryTree = false;
        private bool _stopCopyWhenFileExists = false;
        private bool _reverseCopyWhenFileExists = false;
        private string _stopCopyFileName = "stop.copy";
        private string _reverseCopyFileName = "reverse.copy";

        /// <summary>
        /// 设置文件大小限制控件
        /// </summary>
        private void SetupFileSizeLimitControls()
        {
            checkBox11.CheckedChanged += (s, e) =>
            {
                textBox3.Enabled = checkBox11.Checked;
                if (!checkBox11.Checked) textBox3.Text = string.Empty;
            };
            textBox3.Enabled = checkBox11.Checked;
        }

        /// <summary>
        /// 设置文件名过滤控件
        /// </summary>
        private void SetupFileNameFilterControls()
        {
            checkBox12.CheckedChanged += (s, e) =>
            {
                textBox4.Enabled = checkBox12.Checked;
                UpdateFileNameKeywords();
                if (!checkBox12.Checked) textBox4.Text = string.Empty;
            };

            textBox4.TextChanged += (s, e) => UpdateFileNameKeywords();
            textBox4.Enabled = checkBox12.Checked;
        }

        private void UpdateFileNameKeywords()
        {
            _fileNameKeywords.Clear();

            if (checkBox12.Checked && !string.IsNullOrWhiteSpace(textBox4.Text))
            {
                _fileNameKeywords.AddRange(
                    textBox4.Text.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                    .Select(k => k.Trim())
                    .Where(k => !string.IsNullOrEmpty(k))
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                );
            }
        }

        /// <summary>
        /// 设置文件夹名称过滤控件
        /// </summary>
        private void SetupFolderNameFilterControls()
        {
            checkBox21.CheckedChanged += (s, e) =>
            {
                _filterByFolderName = checkBox21.Checked;
                textBox7.Enabled = checkBox21.Checked;
                UpdateFolderNameKeywords();
                if (!checkBox21.Checked) textBox7.Text = string.Empty;
            };

            textBox7.TextChanged += (s, e) => UpdateFolderNameKeywords();
            textBox7.Enabled = checkBox21.Checked;
        }

        private void UpdateFolderNameKeywords()
        {
            _folderNameKeywords.Clear();

            if (_filterByFolderName && !string.IsNullOrWhiteSpace(textBox7.Text))
            {
                _folderNameKeywords.AddRange(
                    textBox7.Text.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                    .Select(k => k.Trim())
                    .Where(k => !string.IsNullOrEmpty(k))
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                );
            }
        }

        /// <summary>
        /// 设置目录深度控件
        /// </summary>
        private void SetupDirectoryDepthControls()
        {
            checkBox22.CheckedChanged += (s, e) =>
            {
                _createDirectoryTree = checkBox22.Checked;
            };

            checkBox23.CheckedChanged += (s, e) =>
            {
                numericUpDown2.Enabled = checkBox23.Checked;
                if (checkBox23.Checked && numericUpDown2.Value > 0)
                {
                    _maxDirectoryDepth = (int)numericUpDown2.Value;
                }
                else
                {
                    _maxDirectoryDepth = int.MaxValue;
                }
            };

            numericUpDown2.ValueChanged += (s, e) =>
            {
                if (checkBox23.Checked)
                {
                    _maxDirectoryDepth = (int)numericUpDown2.Value;
                }
            };

            numericUpDown2.Enabled = checkBox23.Checked;
        }

        /// <summary>
        /// 设置U盘特殊文件控件
        /// </summary>
        private void SetupUsbSpecialSettingsControls()
        {
            checkBox14.CheckedChanged += (s, e) =>
            {
                _stopCopyWhenFileExists = checkBox14.Checked;
                textBox5.Enabled = checkBox14.Checked;
                if (checkBox14.Checked && !string.IsNullOrWhiteSpace(textBox5.Text))
                {
                    _stopCopyFileName = textBox5.Text.Trim();
                }
            };

            checkBox15.CheckedChanged += (s, e) =>
            {
                _reverseCopyWhenFileExists = checkBox15.Checked;
                textBox6.Enabled = checkBox15.Checked;
                if (checkBox15.Checked && !string.IsNullOrWhiteSpace(textBox6.Text))
                {
                    _reverseCopyFileName = textBox6.Text.Trim();
                }
            };

            textBox5.TextChanged += (s, e) =>
            {
                if (checkBox14.Checked && !string.IsNullOrWhiteSpace(textBox5.Text))
                {
                    _stopCopyFileName = textBox5.Text.Trim();
                }
            };

            textBox6.TextChanged += (s, e) =>
            {
                if (checkBox15.Checked && !string.IsNullOrWhiteSpace(textBox6.Text))
                {
                    _reverseCopyFileName = textBox6.Text.Trim();
                }
            };

            textBox5.Enabled = checkBox14.Checked;
            textBox6.Enabled = checkBox15.Checked;
        }

        /// <summary>
        /// 检查文件名是否通过过滤
        /// </summary>
        private bool PassFileNameFilter(string fileName)
        {
            if (!checkBox12.Checked)
                return true;

            if (_fileNameKeywords.Count == 0)
                return false;

            return _fileNameKeywords.Any(kw =>
                fileName.IndexOf(kw, StringComparison.OrdinalIgnoreCase) >= 0);
        }

        /// <summary>
        /// 检查文件夹名是否通过过滤
        /// </summary>
        private bool PassFolderNameFilter(string folderName)
        {
            if (!_filterByFolderName)
                return true;

            if (_folderNameKeywords.Count == 0)
                return false;

            return _folderNameKeywords.Any(kw =>
                folderName.IndexOf(kw, StringComparison.OrdinalIgnoreCase) >= 0);
        }
    }
}
