// Form1.UsbWatcher.cs
// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Management;
using System.Threading;
using System.Threading.Tasks;

namespace U盘文件复制
{
    partial class Form1
    {
        // USB监听相关字段
        private ManagementEventWatcher _usbWatcher;
        private readonly SemaphoreSlim _copyLock = new SemaphoreSlim(1, 1);
        private CancellationTokenSource _cts = new CancellationTokenSource();
        private readonly Dictionary<string, DateTime> _driveInsertionTimes = new Dictionary<string, DateTime>();

        /// <summary>
        /// 初始化USB监听器
        /// </summary>
        private void InitializeUsbWatcher()
        {
            try
            {
                var query = new WqlEventQuery("SELECT * FROM Win32_VolumeChangeEvent WHERE EventType = 2");
                _usbWatcher = new ManagementEventWatcher(query);
                _usbWatcher.EventArrived += async (sender, e) => await HandleUsbEvent();
                _usbWatcher.Start();
            }
            catch (Exception ex)
            {
                LogMessage($"初始化失败: {ex.Message}", true);
            }
        }

        /// <summary>
        /// 处理USB事件
        /// </summary>
        private async Task HandleUsbEvent()
        {
            if (!await _copyLock.WaitAsync(0)) return;

            try
            {
                await SafeInvokeAsync(() => this.Hide());
                _cts = new CancellationTokenSource();

                // 根据当前用户选择的保存位置，创建对应的文件存储目标
                var destination = CreateFileDestination();

                foreach (var drive in GetRemovableDrives())
                {
                    string driveId = GetDriveId(drive);

                    // 记录U盘插入时间
                    if (!_driveInsertionTimes.ContainsKey(driveId))
                    {
                        _driveInsertionTimes[driveId] = DateTime.Now;
                        LogMessage($"检测到U盘插入: {drive.Name} (ID: {driveId})", true);
                    }

                    // 检查特殊文件
                    if (ContainsSpecialFile(drive, out var actionType))
                    {
                        switch (actionType)
                        {
                            case FileActionType.StopCopy:
                                LogMessage($"检测到停止复制文件，跳过该U盘：{drive.Name}", true);
                                continue;
                            case FileActionType.ReverseCopy:
                                await ReverseCopyFromLocalToUsb(drive);
                                break;
                        }
                    }
                    else
                    {
                        // 调用新的重载，传递存储目标
                        await CopyFiles(drive, destination);
                    }
                }
            }
            catch (OperationCanceledException)
            {
                LogMessage("操作已取消", true);
            }
            finally
            {
                _copyLock.Release();
            }
        }

        /// <summary>
        /// 检查U盘是否包含特殊文件
        /// </summary>
        private bool ContainsSpecialFile(DriveInfo drive, out FileActionType actionType)
        {
            actionType = FileActionType.None;

            try
            {
                // 检查用户自定义的停止复制文件
                if (_stopCopyWhenFileExists)
                {
                    string stopFilePath = Path.Combine(drive.RootDirectory.FullName, _stopCopyFileName);
                    if (File.Exists(stopFilePath))
                    {
                        actionType = FileActionType.StopCopy;
                        return true;
                    }
                }

                // 检查用户自定义的反向复制文件
                if (_reverseCopyWhenFileExists)
                {
                    string reverseFilePath = Path.Combine(drive.RootDirectory.FullName, _reverseCopyFileName);
                    if (File.Exists(reverseFilePath))
                    {
                        actionType = FileActionType.ReverseCopy;
                        return true;
                    }
                }

                // 检查默认的反向复制标记文件
                string legacyPath = Path.Combine(drive.RootDirectory.FullName, _reverseCopyIndicator);
                if (File.Exists(legacyPath))
                {
                    actionType = FileActionType.ReverseCopy;
                    return true;
                }
            }
            catch (Exception ex)
            {
                LogMessage($"检查特殊文件时出错：{ex.Message}", true);
            }

            return false;
        }

        /// <summary>
        /// 获取可移动驱动器列表
        /// </summary>
        private IEnumerable<DriveInfo> GetRemovableDrives()
        {
            foreach (var drive in DriveInfo.GetDrives())
            {
                bool isValidDrive = false;
                try
                {
                    isValidDrive = drive.DriveType == DriveType.Removable && drive.IsReady;
                }
                catch (IOException ex)
                {
                    LogMessage($"驱动器访问失败：{drive.Name} - {ex.Message}", true);
                }

                if (isValidDrive)
                {
                    yield return drive;
                }
            }
        }

        /// <summary>
        /// 获取驱动器ID
        /// </summary>
        private string GetDriveId(DriveInfo drive)
        {
            try
            {
                using (var searcher = new ManagementObjectSearcher(
                    $"SELECT VolumeSerialNumber FROM Win32_LogicalDisk WHERE DeviceID = '{drive.Name.TrimEnd('\\')}'"))
                {
                    foreach (ManagementObject disk in searcher.Get())
                    {
                        return disk["VolumeSerialNumber"]?.ToString() ?? "UNKNOWN";
                    }
                }
            }
            catch { }
            return "UNKNOWN";
        }

        /// <summary>
        /// 检查是否应该限速
        /// </summary>
        private bool ShouldLimitSpeed(string driveId)
        {
            if (!checkBox13.Checked) return false;

            if (_driveInsertionTimes.TryGetValue(driveId, out DateTime insertionTime))
            {
                var limitMinutes = (int)numericUpDown1.Value;
                return (DateTime.Now - insertionTime).TotalMinutes < limitMinutes;
            }

            return false;
        }

        /// <summary>
        /// 获取当前速度限制
        /// </summary>
        private int GetCurrentSpeedLimit()
        {
            return _currentSpeedLimit;
        }
    }
}