// <auto-generated />
// 此文件是 Form1 的部分类模块文件，非设计器文件
using System;
using Microsoft.Win32;
using System.Windows.Forms;

namespace U盘文件复制
{
    partial class Form1
    {
        /// <summary>
        /// 开机自启动控件初始化
        /// </summary>
        private void SetupAutoStartControls()
        {
            // 检查注册表中是否已设置开机自启动，同步 checkBox24 状态
            checkBox24.Checked = IsAutoStartEnabled();

            // 绑定事件
            checkBox24.CheckedChanged += (s, e) =>
            {
                if (checkBox24.Checked)
                {
                    EnableAutoStart();
                }
                else
                {
                    DisableAutoStart();
                }
            };

            // checkBox25 状态改变时，如果已启用开机自启动则更新注册表
            checkBox25.CheckedChanged += (s, e) =>
            {
                if (checkBox24.Checked)
                {
                    EnableAutoStart();
                }
            };
        }

        /// <summary>
        /// 检查是否已启用开机自启动
        /// </summary>
        private bool IsAutoStartEnabled()
        {
            try
            {
                using (RegistryKey key = Registry.CurrentUser.OpenSubKey(AutoStartRegistryKey, false))
                {
                    if (key != null)
                    {
                        object value = key.GetValue(AppName);
                        return value != null;
                    }
                }
            }
            catch (Exception ex)
            {
                LogMessage($"检查开机自启动状态失败: {ex.Message}", true);
            }
            return false;
        }

        /// <summary>
        /// 启用开机自启动
        /// </summary>
        private void EnableAutoStart()
        {
            try
            {
                string exePath = Application.ExecutablePath;
                string arguments = checkBox25.Checked ? "/hidden" : "";
                using (RegistryKey key = Registry.CurrentUser.OpenSubKey(AutoStartRegistryKey, true))
                {
                    if (key != null)
                    {
                        key.SetValue(AppName, $"\"{exePath}\" {arguments}".TrimEnd());
                        LogMessage("开机自启动已启用", true);
                    }
                }
            }
            catch (Exception ex)
            {
                LogMessage($"设置开机自启动失败: {ex.Message}", true);
                checkBox24.Checked = false;
            }
        }

        /// <summary>
        /// 禁用开机自启动
        /// </summary>
        private void DisableAutoStart()
        {
            try
            {
                using (RegistryKey key = Registry.CurrentUser.OpenSubKey(AutoStartRegistryKey, true))
                {
                    if (key != null)
                    {
                        key.DeleteValue(AppName, false);
                        LogMessage("开机自启动已禁用", true);
                    }
                }
            }
            catch (Exception ex)
            {
                LogMessage($"取消开机自启动失败: {ex.Message}", true);
            }
        }
    }
}
